steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/${PROJECT_ID}/my-image-repo/python-flask', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/${PROJECT_ID}/my-image-repo/python-flask']
