---
# Creating Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: gke-prod

---
# Creating deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-devops-deployment
  labels:
    name: gke-devops
  namespace: gke-prod
spec:
  template:
    metadata:
      name: gke-devops
      labels:
        env: prod
        name: gke-devops
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/kodekloud-gcp-training-385911/python-flask:latest
          name: gke-devops
          ports:
          - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
  replicas: 1
  selector:
    matchLabels:
      env: prod
      name: gke-devops

---
# Creating Service
apiVersion: v1
kind: Service
metadata:
  name: gke-service
  namespace: gke-prod
spec:
  type: LoadBalancer
  selector:
    env: prod
    name: gke-devops
  ports:
   - nodePort: 80
     port: 5000
     protocol: TCP
     targetPort: 5000